# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
ENABLE:
  - ACTION
  - BASH
  - COPYPASTE
  - JSON
  - MARKDOWN
  - PYTHON
  - REPOSITORY
  - SPELL
  - YAML

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE_LINTERS:
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY_SBOM
  - SPELL_CSPELL
  # - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
#  - SPELL # Uncomment to disable checks of spelling mistakes

#DISABLE:
SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false
# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

BASH_FILTER_REGEX_INCLUDE: (scripts)
BASH_EXEC_FILE_EXTENSIONS: ["*"]
BASH_SHELLCHECK_FILE_EXTENSIONS: ["*"]
BASH_SHFMT_FILE_EXTENSIONS: ["*"]
