[format]
docstring-code-format = true

[lint]
extend-select = [
  "ARG",  # flake8-unused-arguments
  "B",    # flake8-bugbear
  "BLE",  # flake8-blind-except
  "C4",   # flake8-comprehensions
  "C901", # mccabe
  "FLY",  # flynt
  "FURB", # refurb
  "I",    # isort
  "N",    # pep8-naming
  "PERF", # Perflint
  "PT",   # flake8-pytest-style
  "PTH",  # flake8-use-pathlib
  "RET",  # flake8-return
  "RUF",  # Ruff-specific rules
  "S",    # flake8-bandit
  "SIM",  # flake8-simplify
  "TRY",  # tryceratops
  "UP",   # pyupgrade
  "ERA",  # eradicate,
  "PIE",  # flake8-pie
  "T20",  # flake8-print
  "Q",    # flake8-quotes
  "RSE",  # flake8-raise
  "SLF",
  "SLOT",
  "TID",
  "TCH",
  "LOG",
]
ignore = [
  "D100",   # Missing docstring in public module
  "D104",   # Missing docstring in public package
  "D203",   # 1 blank line required before class docstring
  "D212",   # Multi-line docstring summary should start at the first line
  "S101",   # Use of assert detected
  "TRY003", # Avoid specifying long messages outside the exception class
  "C416",   # Unnecessary `list` comprehension (rewrite using `list()`)
]
mccabe = { max-complexity = 5 }
pydocstyle = { convention = "google" }
