# Generated by CodiumAI
import os

# Dependencies:
# pip install pytest-mock
import pytest
from langchain_core.messages import SystemMessage

from src.ai import AI
from src.exceptions import InvalidTranscript


class MockTranscript:
    def __init__(self, content, metadata):
        self.content = content
        self.metadata = metadata


class MockMetadata:
    def __init__(self, title, publish_date, author, url):
        self.title = title
        self.publish_date = publish_date
        self.author = author
        self.url = url


@pytest.fixture(scope="session")
def valid_transcript(valid_metadata):
    return MockTranscript(
        content="This is the transcript content", metadata=valid_metadata
    )


@pytest.fixture(scope="session")
def short_transcript(valid_metadata):
    return MockTranscript(content="This is a short transcript", metadata=valid_metadata)


@pytest.fixture(scope="session")
def invalid_type_transcript(valid_metadata):
    return MockTranscript(content=123, metadata=valid_metadata)


@pytest.fixture(scope="session")
def valid_metadata():
    return MockMetadata(
        title="Transcript Title",
        publish_date="2022-01-01",
        author="John Doe",
        url="https://example.com/transcript",
    )
