# Generated by CodiumAI
import pytest

from src.transcript import Metadata


class TestMetadata:
    # Metadata object can be created with valid title, publish_date, author, and url.
    def test_valid_metadata_creation(self):
        metadata = Metadata(
            title="Test Title",
            publish_date="2022-01-01",
            author="Test Author",
            url="https://www.example.com",
        )
        assert metadata.title == "Test Title"
        assert metadata.publish_date == "2022-01-01"
        assert metadata.author == "Test Author"
        assert metadata.url == "https://www.example.com"

    # Metadata object can be printed with all its information.
    def test_metadata_printing(self):
        metadata = Metadata(
            title="Test Title",
            publish_date="2022-01-01",
            author="Test Author",
            url="https://www.example.com",
        )
        expected_output = "Title: Test Title\nPublish Date: 2022-01-01\nAuthor: Test Author\nURL: https://www.example.com\n"
        assert metadata.print() == expected_output

    # Metadata object cannot be created with empty title.
    def test_empty_title_metadata_creation(self):
        with pytest.raises(ValueError):
            Metadata(
                title="",
                publish_date="2022-01-01",
                author="Test Author",
                url="https://www.example.com",
            )

    # Metadata object cannot be created with empty author.
    def test_empty_author_metadata_creation(self):
        with pytest.raises(ValueError):
            Metadata(
                title="Test Title",
                publish_date="2022-01-01",
                author="",
                url="https://www.example.com",
            )

    # Metadata object cannot be created with empty url.
    def test_empty_url_metadata_creation(self):
        with pytest.raises(ValueError):
            Metadata(
                title="Test Title",
                publish_date="2022-01-01",
                author="Test Author",
                url="",
            )
