from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from src.transcript import Transcript


class AI:
    """
    This class represents an AI assistant that
    can chat with users and provide output based
    on the conversation.
    """

    def __init__(self, transcript: Transcript) -> None:
        """
        Initializes an instance of the class.

        Args:
            transcript (str): The transcript of the video.

        Returns:
            None
        """
        self.transcript = transcript.content
        self.metadata = transcript.metadata

    def print_takeaways(self) -> None:
        chat = ChatOpenAI(temperature=0)
        messages = [
          SystemMessage(content=(
                  "The user will provide a transcript."
                  "From the transcript, you will provide a bulleted list of "
                  "key takeaways. At the top of the list, add a title: "
                  f"'# Key Takeaways — {self.metadata.title}'")),
          HumanMessage(content=self.transcript),
        ]
        for chunk in chat.stream(messages):
            print(chunk.content, end="", flush=True)
        print()
        print("---")

    def print_summary(self ) -> None:
        """
        Prints the output generated by the AI assistant
        based on the conversation with the user.
        """
        chat = ChatOpenAI(temperature=1)
        messages = [
            SystemMessage(
                content=(
                  "The user will provide a transcript.Copy edit the transcript "
                  "for clarity, accuracy, and basic errors. "
                  "reformat the transcript  into an in-depth "
                  "markdown blog post using sections and section headers."
                  f"The title of the blog post will be {self.metadata.title}."
                )
            ),
            HumanMessage(content=self.transcript),
        ]
        for chunk in chat.stream(messages):
            print(chunk.content, end="", flush=True)
        print()
        print("---")

