name: CI
on:
  push:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v1
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
      - name: Do testing stuff
        run: rye run python -m pytest --junit-xml=./results/pytest.xml --cov=./ --cov-report xml -v
      - name: Push result to Testspace server
        run: |
          testspace ./results/*.xml coverage.xml
        if: always()
