name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
      - name: Do testing stuff
        run: poetry run pytest --junit-xml=./results/pytest.xml --cov=./ --cov-report xml -v
      - name: Push result to Testspace server
        run: |
          testspace ./results/*.xml coverage.xml
        if: always()
